# This is a basic workflow that is manually triggered

name: Triggered workflow to pass branch to new repo

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        required: true
        default: "no branch was given"
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'Sam Adams'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Manual Workflow successfully for ${{ github.event.inputs.name }}"
    - name: Name branch
      run: echo "Branch is ${{ github.event.inputs.branch }}"
    # - name: Invoke workflow in another repo and pass the branch name
    #     uses: benc-uk/workflow-dispatch@v1
    #     with:
    #       repo: chillianosson/action-practice-2
    #       workflow: receiving-workflow.yml
    #       inputs: '{ "branch": "${{ env.branch }}" }'
    - name: Invoke workflow in another repo with inputs
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: receiving-workflow.yml
        repo: chillianosson/action-practice-2
        inputs: '{ "branch": "${{ env.branch }}" }'

